name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-on-ubuntu:

    runs-on: ubuntu-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          cmake --install .

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact_ubuntu
          path: install/*

  build-on-windows:

    runs-on: windows-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
          cmake --install .

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact_windows
          path: install/*

  build-on-macos:

    runs-on: macos-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          cmake --install .

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact_macos
          path: install/*
